- hosts: filrouge
  become: yes
  vars:
    app_dir: /home/azureuser/todo-app
  tasks:
    - name: Mettre à jour apt et installer dépendances
      apt:
        update_cache: yes
        name:
          - python3-pip
          - docker.io
          - docker-compose
          - git
        state: present

    - name: Ajouter utilisateur au groupe docker
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Cloner le dépôt GitHub de l'application
      git:
        repo: 'https://github.com/Ymed95/projetUL'
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Copier fichier .env dans le dossier app
      copy:
        src: ../../.env
        dest: "{{ app_dir }}/.env"
        mode: '0644'
    

    - name: Créer le dossier data s'il n'existe pas
      file:
        path: "{{ app_dir }}/app/data"
        state: directory
        mode: '0777'


    - name: S'assurer que le dossier data appartient à l'utilisateur du conteneur (UID 1000)
      file:
        path: "{{ app_dir }}/app/data"
        owner: 1000
        group: 1000
        recurse: yes

    - name: Donner tous les droits sur le dossier data
      file:
        path: "{{ app_dir }}/app/data"
        mode: '0777'
        recurse: yes

    - name: Lancer docker-compose
      shell: docker-compose up -d --build
      args:
        chdir: "{{ app_dir }}"

    - name: Lancer docker-compose
      shell: docker-compose up -d --build
      args:
        chdir: "{{ app_dir }}"


    - name: Afficher les conteneurs Docker en cours d'exécution
      shell: docker ps
      register: docker_ps_result

    - name: Afficher le résultat de docker ps
      debug:
        var: docker_ps_result.stdout_lines

